### ISSUE TITLE
How should I choose all markers?

### ISSUE THREAD

**Issue by zorrodong** [mahmoudibrahim/genesorteR#1]
Hi, 

Thanks very much for such a wonderful tool to quickly find the DEGs.

However, if I want to extract all the DEGs of a cluster or all cluster, what cutoff of specScore should I use, or I have to use the adj_pvalue to measure? And if I use the pvalue, I have to extract the DEGs by myself, kind of not convenient,  will you consider adding this function?

Looking forward to your reply!

Zorro
20190706

**Comment by mahmoudibrahim** [comment]
hi
thank you so much for the suggestion! I agree with you that a function that organizes the output of sortGenes and getPValues together in a single tidy table is a nice idea and I will update this issue as soon as I have written it. 

Until then, please see below and feel free to post any further questions!


the specScore matrix can be used to rank genes in each clusters, to estimate a cutoff to get all variable (differentially expressed genes, DEGs) I would go for the "adjpval" matrix from getPValues. 

 if "sg" is the output of "sortGenes()", this will give you the top 10 genes in each cluster:
`plotTopMarkerHeat(sg, top_n = 10, outs = TRUE, plotheat = FALSE)` 

to get a small set of marker genes:
`getMarkers(sg)`

To get all variable genes:
`pp=getPValues(sg)`
`names(which(apply(pp$adjpval, 1, function(x) any(x < 0.05))))`

to get all marker genes for say cluster 1:
`rownames(pp$adjpval[which(pp$adjpval[,1] < 0.05),])`

**Comment by zorrodong** [comment]
Thanks for the prompt reply, actually, I have already done what you said. 
Again, It is really a fast method, I really like it!

Best wishes,

Zorro

**Comment by mahmoudibrahim** [comment]
hi

there is now a new function in the latest release called getTable to summarize variable genes and fold change values. I would recommend now to run something like this to get all variable genes:

`gs = sortGenes(kidneyTabulaMuris$exp, kidneyTabulaMuris$cellType)`
`pp = getPValues(gs)`
`tab = getTable(gs, pp)`

to get a small list of marker genes:
`mm = getMarkers(gs)`

I'm closing the issue now, however feel free to reopen or open a new one if you have any further questions.

best wishes
Mahmoud
